[project]
name = "xyte-mcp-alpha"
version = "1.0.0"
description = "MCP server for Xyte organization API"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mcp[cli]>=1.1.0",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "cachetools>=5.3.0",
    "prometheus-client>=0.19.0"
]

[project.scripts]
serve = "xyte_mcp_alpha:serve"

[project.urls]
Homepage = "https://github.com/portons/xyte-mcp-alpha"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/xyte_mcp_alpha"]

[tool.ruff]
line-length = 100
