[project]
name = "xyte-mcp-alpha"
version = "0.1.0"
description = "Xyte MCP Alpha"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/yourusername/xyte-mcp-alpha"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/xyte_mcp_alpha"]
