{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xyte-mcp
spec:
  rules:
  - host: {{ index .Values.ingress.hosts 0 }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xyte-mcp
            port:
              number: {{ .Values.service.port }}
  tls:
{{- range .Values.ingress.tls }}
  - hosts:
{{- range .hosts }}
    - {{ . }}
{{- end }}
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
