apiVersion: v1
kind: Secret
metadata:
  name: xyte-secrets
stringData:
{{- if .Values.env.XYTE_API_KEY }}
  api_key: {{ .Values.env.XYTE_API_KEY | quote }}
{{- end }}
{{- if .Values.env.XYTE_USER_TOKEN }}
  user_token: {{ .Values.env.XYTE_USER_TOKEN | quote }}
{{- end }}
{{- if .Values.env.XYTE_OAUTH_TOKEN }}
  oauth_token: {{ .Values.env.XYTE_OAUTH_TOKEN | quote }}
{{- end }}
