{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyte-mcp-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: xyte-mcp-worker
  template:
    metadata:
      labels:
        app: xyte-mcp-worker
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["celery", "-A", "xyte_mcp.celery_app", "worker", "-Q", "long", "-c", "2"]
        env:
        {{- if not .Values.multiTenant }}
        - name: XYTE_API_KEY
          valueFrom:
            secretKeyRef:
              name: xyte-secrets
              key: api_key
        {{- end }}
        {{- if .Values.env.XYTE_USER_TOKEN }}
        - name: XYTE_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: xyte-secrets
              key: user_token
        {{- end }}
        {{- if .Values.env.XYTE_OAUTH_TOKEN }}
        - name: XYTE_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: xyte-secrets
              key: oauth_token
        {{- end }}
        envFrom:
        - configMapRef:
            name: xyte-config
        resources:
{{ toYaml .Values.worker.resources | indent 10 }}
{{- end }}
