apiVersion: v1
kind: ConfigMap
metadata:
  name: xyte-config
data:
  XYTE_BASE_URL: "https://hub.xyte.io/core/v1/organization"
  XYTE_CACHE_TTL: "60"
  XYTE_ENV: "prod"
  XYTE_RATE_LIMIT: "60"
  MCP_INSPECTOR_PORT: "8080"
