name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install .
          pip install ruff pytest pytest-cov
      - name: Format code with ruff
        run: |
          ruff check src tests --fix
          git diff --exit-code || (echo "Code was formatted. Please run 'ruff check --fix' locally and commit the changes." && exit 1)
      - name: Run static analysis
        run: ruff check src tests
      - name: Run tests
        run: pytest --cov=src --cov-report=xml
      - name: Security scan
        run: scripts/security_scan.sh || true
