name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          echo "XYTE_API_KEY=test-api-key" >> $GITHUB_ENV
          echo "XYTE_ENV=test" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install .
          pip install ruff mypy pytest pytest-cov coverage bandit
          pip install types-cachetools types-certifi
      - name: Check code formatting and lint with ruff
        run: ruff check src tests
      - name: Type checks
        run: mypy src || true
      - name: Run Bandit security scan
        run: bandit -r src -ll
      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
      - name: Build Docker image
        run: docker build -t xyte-mcp-alpha:${{ github.sha }} .
      - name: Security scan
        run: scripts/security_scan.sh || true
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.4.1
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: 1

  publish:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}