name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install .
          pip install ruff mypy pytest pytest-cov coverage
      - name: Format code with ruff
        run: |
          ruff check src tests --fix
          git diff --exit-code || (echo "Code was formatted. Please run 'ruff check --fix' locally and commit the changes." && exit 1)
      - name: Lint
        run: ruff check src tests
      - name: Type checks
        run: mypy src || true
      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
      - name: Build Docker image
        run: docker build -t xyte-mcp-alpha:${{ github.sha }} .
      - name: Security scan
        run: scripts/security_scan.sh || true

  publish:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
